name: wt_models
description: Package to assist with transforming model data into different formats.
version: 1.0.0+1
publish_to: 'none'
homepage: https://github.com/tmcmaster/wt_models

environment:
  sdk: '>=3.0.0 <4.0.0'

# Scripts to be run with rps
scripts:
  init: flutter pub get
  clean: flutter clean
  refresh: flutter clean; flutter pub get
  test: flutter test
  analise: flutter analyze
  freezed:
    build: dart run build_runner build --delete-conflicting-outputs
  coverage:
    generate: ./bin/generate_coverage.sh
    view: open coverage/html/index.html

dependencies:
  csv:
  flutter:
    sdk: flutter
  wt_logging:
    git:
      url: git@github.com:tmcmaster/wt_logging.git

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  freezed_annotation:
  json_annotation: ^4.8.1
  json_serializable:
