name: wt_models
description: Package to assist with transforming model data into different formats.
version: 0.0.1
publish_to: 'none'
homepage: https://github.com/tmcmaster/wt_models

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  csv: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
