name: wt_models_examples
description: Example for the wt_models library
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.29.2'

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  freezed:
  freezed_annotation:
  json_annotation: ^4.8.1
  json_serializable:
  wt_logging:
    git:
      url: git@github.com:tmcmaster/wt_logging.git
  wt_models:
    path: ..

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true