name: wt_models_examples
description: Example for the wt_models library
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed:
  freezed_annotation:
  json_serializable:
  cupertino_icons:
  wt_models:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:

flutter:
  uses-material-design: true